name: Test and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image for Test
      run: docker build -t docmara/myapp-test .

    - name: Run Pytest in Docker
      run: docker run --rm docmara/myapp-test

    - name: Login to DockerHub
      if: success()
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image to DockerHub
      if: success()
      run: docker push docmara/myapp-test

